# Generated by Django 6.0 on 2026-01-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_technology_alter_project_options_document_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tech_stack',
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='document',
            name='language',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='live_link',
        ),
        migrations.DeleteModel(
            name='ProjectFile',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
