# Generated by Django 6.0 on 2026-01-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_slug_project_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(default='Python, Django', help_text='e.g. React, Tailwind, Python', max_length=200),
        ),
    ]
